version: 2
jobs:
  test:
    working_directory: ~/logback-throttle

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
    - checkout
    - restore_cache:
        key: logback-throttle-dependencies-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline # gets the project dependencies
    - save_cache:
        paths:
        - ~/.m2
        key: logback-throttle-dependencies-{{ checksum "pom.xml" }}
    - run: mvn test
    - store_test_results:
        path: target/surefire-reports

  deploy:
    working_directory: ~/logback-throttle

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
    - checkout
    - restore_cache:
        key: logback-throttle-dependencies-{{ checksum "pom.xml" }}
    - run:
        name: Deploy release
        command: |
          git version
          BASE_VERSION=0.1
          LATEST_INCREMENT=-1
          LATEST_COMMIT_HASH=$(git rev-list --tags=release/${BASE_VERSION}.* --max-count=1)
          if [ -n "${LATEST_COMMIT_HASH}" ]; then
              LATEST_TAG=$(git describe --tags ${LATEST_COMMIT_HASH});
              LATEST_INCREMENT=$(echo ${LATEST_TAG}|sed 's/.*\.//');
          fi
          NEW_INCREMENT=$((LATEST_INCREMENT + 1))
          VERSION="${BASE_VERSION}.${NEW_INCREMENT}"
          echo "Deploying version ${VERSION}"
          git tag "release/$VERSION"
          git push origin master --tags
          mvn versions:set -DnewVersion=${VERSION}
          mvn deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - test
    - deploy:
        requires:
        - test
